version: "3"
services:
  latest:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./:/rstw_api_volume
    image: rstw_api_image
    container_name: rstw_api_container
    # environment:
    #   - PORT = 8081
    env_file:
      - ./.env
    restart: always
